AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'gemfiles/*'

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Gemspec/RequireMFA:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/WordArray:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/support/seed.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/MemoizedInstanceVariableName:
  Enabled: false
